name: Call Release Solution Workflow
on:
  workflow_dispatch:
#    types:
#      - published

jobs:

  call-release-workflow:
    uses: ./.github/workflows/release-solution-to-prod-reusable.yml
    secrets:
      BUILD_ENVIRONMENT_URL: ${{ vars.BUILD_ENVIRONMENT_URL }}  
      PRODUCTION_ENVIRONMENT_URL: ${{ vars.PRODUCTION_ENVIRONMENT_URL }}  
      CLIENT_ID: ${{ vars.CLIENT_ID }} 
      TENANT_ID: ${{ vars.TENANT_ID }}  
      envSecret: ${{ secrets.PowerPlatformSPN }}
