
name: Call Release Solution Workflow
on:
  push:
    branches:
      - main
  release:
    types:
      - published
jobs:

  call-release-workflow:
    uses: ./.github/workflows/release-solution-to-prod-reusable.yml
    with:
      solution_name:          ${{inputs.solution_name}}
      BUILD_ENVIRONMENT_URL: ${{ vars.BUILD_ENVIRONMENT_URL }}  
      PRODUCTION_ENVIRONMENT_URL: ${{ vars.PRODUCTION_ENVIRONMENT_URL }}  
    
    secrets:

      CLIENT_ID: ${{ vars.CLIENT_ID }} 
      TENANT_ID: ${{ vars.TENANT_ID }}  
      envSecret: ${{ secrets.PowerPlatformSPN }}
