name: Call Release Solution Workflow
on:
  workflow_dispatch:
#    types:
#      - published

jobs:

  call-release-workflow:
    uses: ./.github/workflows/change_deployment.yml
    with:
      BUILD_ENVIRONMENT_URL: vars.BUILD_ENVIRONMENT_URL
      PRODUCTION_ENVIRONMENT_URL: vars.PRODUCTION_ENVIRONMENT_URL

    secrets:
      TENANT_ID: vars.TENANT_ID
      CLIENT_ID: vars.CLIENT_ID
      envSecret: ${{ secrets.PowerPlatformSPN }}
