name: Call Release Solution Workflow
on:
  workflow_dispatch:
#    types:
#      - published
permissions:
  contents: write
jobs:

  call-release-workflow:
    uses: ./.github/workflows/release-solution-to-prod-reusable.yml
    secrets:
      BUILD_ENVIRONMENT_URL: 'https://org5569b62d.crm15.dynamics.com'
      PRODUCTION_ENVIRONMENT_URL: 'https://orgdc49fd0d.crm15.dynamics.com'
      CLIENT_ID: vars.CLIENT_ID
      TENANT_ID: vars.TENANT_ID
      envSecret: ${{ secrets.PowerPlatformSPN }}
