name: export-and-branch-solution
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the solution to be worked on from Power Platform'
        required: true
        default: powerappsol
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
        description: 'folder name to be created and checked in *do not change*'
        required: true
        default: solutions/
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Install PAC CLI
      uses: microsoft/powerplatform-actions/actions-install@v1
      with:
        cloud: 'Public'
 
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{secrets.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{secrets.PowerPlatformSPN}}
        tenant-id: ${{secrets.TENANT_ID}}
 
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{secrets.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: powerappsol
        solution-output-file: out/exported/powerappsol.zip
 
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: out/exported/powerappsol.zip
        solution-folder: out/solutions/powerappsol
        solution-type: 'Unmanaged'
        overwrite-files: true
 
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/powerappsol
        solution-target-folder: solutions/powerappsol
        repo-token: ${{ secrets.ACCESS_SECRET }}
        allow-empty-commit: true

    - name: Add Jira Issue Key to Commit and Log to Jira
      run: |
        issue_key="SCRUM-1"
        
        # Create a commit message with Jira issue key
        git config --global user.name "Mahnoor"
        git config --global user.email "mahnnoorriaz300@gmail.com"
        git commit -m "Export and unpack solution for Jira Issue: $issue_key"
        git push


