name: export-and-branch-solution
on:
  push:
    branches: 
      - main
    inputs:
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
        description: 'folder name to be created and checked in *do not change*'
        required: true
        default: solutions/
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Install PAC CLI
      uses: microsoft/powerplatform-actions/actions-install@v1
      with:
        cloud: 'Public'
 
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{secrets.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{secrets.PowerPlatformSPN}}
        tenant-id: ${{secrets.TENANT_ID}}
 
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{secrets.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: ${{vars.SOLUTION_NAME}}
        solution-output-file: out/exported/${{vars.SOLUTION_NAME}}.zip
 
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: out/exported/${{vars.SOLUTION_NAME}}.zip
        solution-folder: out/solutions/${{vars.SOLUTION_NAME}}
        solution-type: 'Unmanaged'
        overwrite-files: true

   # Branch-solution step generates the branch name dynamically
    - name: branch-solution, prepare it for a PullRequest
      id: branch-solution
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/${{vars.SOLUTION_NAME}}
        solution-target-folder: solutions/SCRUM-1-${{vars.SOLUTION_NAME}}
        repo-token: ${{ secrets.ACCESS_SECRET }}
        allow-empty-commit: true

    - name: Check all outputs from branch-solution
      run: |
        echo "branch-solution outputs: ${{ toJson(steps.branch-solution.outputs) }}"
        
   # Capture branch name from logs using a regex pattern in PowerShell
    - name: Capture branch name from the previous step's output
      id: capture-branch
      run: |
        # Use the output of the 'branch-solution' step to extract the branch name
        $branchName = "${{ steps.branch-solution.outputs.branch-name }}"
        
        # Check if the branch name is captured successfully
        echo "Branch name captured: $branchName"
        
        # Set the captured branch name as an environment variable
        echo "BRANCH_NAME=$branchName" >> $GITHUB_ENV
        
    # Create Pull Request to main from the dynamically generated branch
    - name: Create Pull Request to main
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.ACCESS_SECRET }}
        base: main
        head: ${{ env.BRANCH_NAME }}
        title: 'Auto PR from branch ${{ env.BRANCH_NAME }}'
        body: 'This is an automatically generated pull request from the branch ${{ env.BRANCH_NAME }}.'
