name: Create and Merge Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  create_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.name "Mahnoor"
          git config --global user.email "mahnoorriaz300@gmail.com"

      - name: Create a new branch
        run: |
          # Define a new branch name
          NEW_BRANCH="feature/$(date +%Y%m%d%H%M%S)"
          git checkout -b $NEW_BRANCH
          echo "Created new branch: $NEW_BRANCH"

      - name: Make changes (Optional)
        run: |
          # Here you can modify files, add new files, etc.
          echo "Making some changes..."
          touch newfile.txt
          echo "This is a new file created during the workflow." > newfile.txt
          git add newfile.txt

      - name: Commit changes
        run: |
          git commit -m "Add new file from GitHub Actions workflow"

      - name: Push the new branch to GitHub
        run: |
          git push https://x-access-token:${{ secrets.ACCESS_SECRET }}@github.com/${{ github.repository }} $NEW_BRANCH
      - name: Checkout the main branch
        run: |
          git checkout main
          git pull origin main

      - name: Merge the new branch into main
        run: |
          git merge $NEW_BRANCH

      - name: Push merged changes to main
        run: |
          git push https://x-access-token:${{ secrets.ACCESS_SECRET }}@github.com/${{ github.repository }} main
