name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  workflow_dispatch      
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/Release-Soloution-to-prod-reusable.yml
    with:
      #You can specify the solution name here
      solution_name: devsol
      #Update your values here
      BUILD_ENVIRONMENT_URL: ${{secrets.ENVIRONMENT_URL}}
      PRODUCTION_ENVIRONMENT_URL: ${{secrets.PRODUCTION_ENVIRONMENT_URL}}
      CLIENT_ID: ${{secrets.APP_ID}}
      TENANT_ID: ${{secrets.TENANT_ID}}    
    secrets:
      envSecret: ${{secrets.PowerPlatformSPN}}
