name: Call Release Solution Workflow
on:
 release:
    types:
      - published  # Trigger when a release is published
jobs:
  call-release-workflow:
    uses: ./.github/workflows/reusable_test.yml  
    secrets:
      BUILD_ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}  
      PRODUCTION_ENVIRONMENT_URL: ${{ secrets.PRODUCTION_ENVIRONMENT_URL }}  
      CLIENT_ID: ${{ secrets.CLIENT_ID }} 
      TENANT_ID: ${{ secrets.TENANT_ID }}  
      envSecret: ${{ secrets.PowerPlatformSPN }}  

