name: Call Release Solution Workflow
on:
  workflow_dispatch:
jobs:
  call-release-workflow:
    uses: ./.github/workflows/Release-Soloution-to-prod-reusable.yml  # Replace with the actual path and branch
    secrets:
      BUILD_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}  # Secret reference for build environment URL
      PRODUCTION_ENVIRONMENT_URL: ${{ secrets.PRODUCTION_ENVIRONMENT_URL }}  # Secret reference for production environment URL
      CLIENT_ID: ${{ secrets.CLIENT_ID }}  # Secret reference for client id
      TENANT_ID: ${{ secrets.TENANT_ID }}  # Secret reference for tenant id

      envSecret: ${{ secrets.PowerPlatformSPN }}  # Secret reference for SPN authentication
